kind: pipeline
type: docker
name: cxscan

steps:
- name: Run Checkmarx Scan
  image: openjdk:11.0.5
  commands:
    - wget -q -O ~/cxcli.zip https://download.checkmarx.com/9.0.0/Plugins/CxConsolePlugin-$CX_CLI_VERSION.zip 
    - unzip -q ~/cxcli.zip -d ~/cxcli 
    - rm -rf ~/cxcli.zip 
    - chmod +x ~/cxcli/runCxConsole.sh
    - export CX_PROJECT_NAME=$(basename "$DRONE_REPO")
    - ~/cxcli/runCxConsole.sh Scan -CxServer $CX_SERVER -CxUser $CX_USER -CxPassword $CX_PASSWORD -ProjectName "$CX_TEAM/$CX_PROJECT_NAME-$DRONE_BRANCH" -preset "$CX_PRESET" -LocationType folder -LocationPath $DRONE_WORKSPACE -SASTHigh $CX_HIGH -SASTMedium $CX_MEDIUM -SASTLow $CX_LOW -ReportXML results-$CX_PROJECT_NAME-$DRONE_BRANCH.xml -ReportPDF results-$CX_PROJECT_NAME-$DRONE_BRANCH.pdf -Comment "git $DRONE_BRANCH@$DRONE_COMMIT" -verbose
  environment:
    CX_SERVER:
      from_secret: cx_server
    CX_USER: 
      from_secret: cx_user
    CX_TEAM:
      from_secret: cx_team
    CX_PRESET: Checkmarx Default
    CX_HIGH: 0
    CX_MEDIUM: 0
    CX_LOW: 0
    CX_CLI_VERSION:
      from_secret: cx_cli_version
    CX_PASSWORD:
      from_secret: cx_password
