kind: pipeline
type: docker
name: cxscan

steps:
- name: Run Checkmarx Scan
  image: checkmarx/cx-flow:1.6.12
  commands:
    - export CX_PROJECT_NAME=$(basename "$DRONE_REPO")
    - java -Xms512m -Xmx2048m -Djava.security.egd=file:/dev/./urandom -jar /app/cx-flow.jar --scan --f=$DRONE_WORKSPACE --cx-project=$CX_PROJECT_NAME-$DRONE_BRANCH --namespace=$CX_PROJECT_NAME --app=$CX_PROJECT_NAME --repo-name=$CX_PROJECT_NAME --branch=$DRONE_BRANCH --cx-flow.enabled-vulnerability-scanners=$CX_VULNERABILITY_SCANNERS --cx-flow.bug-tracker=$CX_BUG_TRACKER --cx-flow.bug-tracker-impl=$CX_BUG_TRACKER --checkmarx.multi-tenant=$CX_IS_MULTI_TENANT --checkmarx.base-url=$CX_SERVER --checkmarx.version=$CX_VERSION --checkmarx.preset="$CX_PRESET" --checkmarx.team="$CX_TEAM" --checkmarx.username=$CX_USER --checkmarx.password=$CX_PASSWORD --checkmarx.client-id=$CX_CLIENT_ID --checkmarx.client-secret=$CX_CLIENT_SECRET --checkmarx.scope="$CX_SCOPE" --checkmarx.configuration="$CX_CONFIGURATION" --checkmarx.exclude-folders="$CX_EXCLUDE_FOLDERS" --checkmarx.exclude-files="$CX_EXCLUDE_FILES"
  environment:
    CX_SERVER:
      from_secret: cx_server
    CX_USER: 
      from_secret: cx_user
    CX_TEAM:
      from_secret: cx_team
    CX_VERSION: 9.2
    CX_CLIENT_ID: resource_owner_client
    CX_SCOPE: sast_rest_api
    CX_CLIENT_SECRET: 
      from_secret: cx_client_secret
    CX_PRESET: Checkmarx Default
    CX_CONFIGURATION: Default Configuration
    CX_EXCLUDE_FOLDERS: .git,.idea,node_modules,tests,test,androidTest
    CX_EXCLUDE_FILES: *.md,*.min.js
    CX_VULNERABILITY_SCANNERS: sast
    CX_IS_MULTI_TENANT: false
    CX_BUG_TRACKER: Json
    CX_PASSWORD:
      from_secret: cx_password
