trigger:
- master

pool:
  vmImage: 'win1803'

steps:
- task: Security static source code analysis@88
  inputs:
    CheckmarxService: 'https://cxprivatecloud.checkmarx.net'
    projectName: 'AzureDevopsTest'
    preset: 'Checkmarx Default'
    fullTeamName: '\CxServer\SP\EMEA\__psteam'
    incScan: false
    vulnerabilityThreshold: false
