
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Security static source code analysis@2019
  inputs:
    CheckmarxService: 'Checkmarx'
    projectName: 'AzureDevops SAST Test'
    preset: 'Checkmarx Default'
    fullTeamName: '\CxServer\SP\EMEA\__psteam'
    incScan: false
    vulnerabilityThreshold: false
